### ISSUE TITLE
androidTestApi is obsolete

### ISSUE THREAD

**Issue by tim4dev** [facebook/screenshot-tests-for-android#187]
Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.

**Comment by xiphirx** [comment]
You seem to be using an older version of the library. We set add it to `androidTestImplementation` https://github.com/facebook/screenshot-tests-for-android/blob/master/plugin/src/main/kotlin/com/facebook/testing/screenshot/build/ScreenshotsPlugin.kt#L52

**Comment by JamesScottTAB** [comment]
I also get this warning when using 0.7.0.

I checked out commit c5fc63ceffb20a718c38d4b4320286e1e61e9622 which is tagged as the latest release and this appears to be before the above linked changes removing "androidTestApi". Is a release planned soon?

**Comment by yayaa** [comment]
I think it must be released before "end of 2018" as error states, otherwise this library will not be able to used anymore. 🤷‍♂️  

> Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Please release soon, so we can update, and keep using the library 🙏
