### ISSUE TITLE
Question: custom measure/layout/draw vs Android one

### ISSUE THREAD

**Issue by marwinxxii** [facebook/screenshot-tests-for-android#193]
Hi everyone,

Could you give more information, why did you decide to stick with custom measure/layout/draw implementation, instead of using Android one?
Why is it more deterministic and faster?

Have you thought about using Espresso, to avoid unwanted side effects from animations and handler callbacks?
When running actions on views with espresso, it ensures, that there are no callbacks in the loop.
For example, because of that, ripple animations on view click are deterministic and have final state.

Also, recently there was introduced support for taking screenshots (which supports views too):

https://developer.android.com/reference/android/support/test/runner/screenshot/Screenshot

It doesn't use tiling to save screenshots, but can you give an example, when tiling is preferred/only way to achieve this?

**Comment by xiphirx** [comment]
>Could you give more information, why did you decide to stick with custom measure/layout/draw implementation, instead of using Android one?
Why is it more deterministic and faster?

The custom / simulated measure / layout / draw doesn't depend on being on the main thread, which the standard pipeline does. This means the process and your test code are on the same thread instead of having the view's draw pass be on the main thread while your test code is on a separate thread, trying to determine if the view is done with its draw pass. 

>Have you thought about using Espresso, to avoid unwanted side effects from animations and handler callbacks?
When running actions on views with espresso, it ensures, that there are no callbacks in the loop.
For example, because of that, ripple animations on view click are deterministic and have final state.

We can handle these in our library as well since we control the thread the view's draw pass is running on. I haven't evaluated the recent additions to espresso though.

>It doesn't use tiling to save screenshots, but can you give an example, when tiling is preferred/only way to achieve this?

Tiling is there to prevent out of memory exceptions when capturing screenshots of extremely large views. Instead of allocating one giant bitmap, we can allocate multiple small bitmaps in succession.


Generally speaking, this library has existed for quite a while, it seems like the espresso screenshot capture stuff is recent and still in beta.

**Comment by marwinxxii** [comment]
> Tiling is there to prevent out of memory exceptions when capturing screenshots of extremely large views. Instead of allocating one giant bitmap, we can allocate multiple small bitmaps in succession.

So, you do use it to screenshot large views? Like newsfeed (or any other long scrollable views), maybe?

**Comment by xiphirx** [comment]
Yes it can be used to screenshot large views, like the entirety of a RecyclerView.

**Comment by xiphirx** [comment]
Closing since it seems like I answered your questions. Feel free to comment if not.
