### ISSUE TITLE
Screenshot names always unknown_unknown.png when call record method inside lambda expression

### ISSUE THREAD

**Issue by mnayef95** [facebook/screenshot-tests-for-android#246]
I'm using new ActivityScenario to launch the activity and inside `onActivity` I'm calling `Screenshot.snapActivity(activity).record()` and the result will be `unknown_image.png`

```
class AndroidTestActivityTest{

    private val activityScenario by lazy { launchActivity<TestActivity>() }

    @Test
    fun doScreenshot() {
        activityScenario.onActivity { activity ->
            Screenshot.snapActivity(activity).record()
        }
    }
}
```

**Comment by xiphirx** [comment]
This is because the library looks for the first non test class to infer the test name from. Since you're wrapping your test code in an anonymous class we dont get any class name info. In this case you can pass `.setName(something)` explicitly to `Screenshot.snapActivity(activity).setName(something).record()`
