### ISSUE TITLE
Malformed metadata.xml file when running under firebase test lab with many tests

### ISSUE THREAD

**Issue by w4-sjcho** [facebook/screenshot-tests-for-android#54]
I get a malformed metadata.xml file when I run the screenshot tests under firebase test lab.

```
RuntimeError: Unable to parse metadata file, this commonly happens if you did not call ScreenshotRunner.onDestroy() from your instrumentation
```

I'm very sure that we're calling `ScreenshotRunner.onDestroy()`, and have confirmed this by logging.

The metadata.xml file end like:
```
...</relative_file_name></screenshot>
```

All data up to </screenshot> is well formed. However not all the test names are included.

This does not happen when running locally, or when the # of test cases are small. (around 15~20)

**Comment by dimorinny** [comment]
I found, that Firebase Testlab sometimes moves data from device to result bucket. After this move screenshot library module can't append data to metadata.xml because this file already removed.

I fixed this problem by storing information about screenshots in memory and flush it, when runner will be destroyed.

You can see this changes here: https://github.com/dimorinny/screenshot-tests-for-android

I don't sure, that I should create pull request for this case, because it is problem of Firebase Testlab.
