### ISSUE TITLE
Animation timing issues when using TextInputLayout

### ISSUE THREAD

**Issue by udeyrishi** [facebook/screenshot-tests-for-android#60]
I have a `TextInputLayout` containing an `AppCompatAutoCompleteTextView` in one of the views I'm testing:

```xml
...
<android.support.design.widget.TextInputLayout
            android:id="@+id/text_input_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.v7.widget.AppCompatAutoCompleteTextView
                android:id="@+id/edit_text"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:saveEnabled="false"/>
</android.support.design.widget.TextInputLayout>
...
```

I'm noticing some timing issues in the screenshots that are being generated. If I call `setText()` as is, I get this in the screenshot (notice the hint-text overlap):

<img width="456" alt="screen shot 2017-03-25 at 6 50 04 pm" src="https://cloud.githubusercontent.com/assets/4692593/24327341/e2d67604-118b-11e7-9481-8ef3da082b35.png">

However, this doesn't happen if I call `Thread.sleep(100)` after calling `setText()` but before `ViewHelpers.setupView().layout()` and `Screenshot.snap(view).record()`. This also doesn't happen if I have other rendering steps following the `setText()` call in some other views that reuse the above XML. Am I missing something?

**Comment by tdrhq** [comment]
Hmm. I haven't used AppCompatAutoCompleteTextView. Here are a few things you can try:

1. Run the entire test on the UI thread -- it's possible that the view is posting things on the handler thread . I couldn't see anything obvious in the source code, but it's worth trying because it's an easy fix. (make sure the view is also constructed on the UI thread)

2. If the above doesn't work, then the view is using the clock directly to determine animation, I've mostly not seen android views do that, though we've encountered a bunch of custom views built internally that does things like that. If this is the case, the solution would involve changing the AppCompatAutoCompleteTextView source code

**Comment by udeyrishi** [comment]
Running the entire test on the main thread doesn't seem to fix the issue. So it's either (2) or something else

**Comment by tdrhq** [comment]
Yeah, unfortunately I don't want to go about debugging issues with specific views, because there can be way too many of these edge cases. But if you have a suggestions on how I might fix this, I could try to do that. Or, you could document how you worked around this in this task for future readers

**Comment by udeyrishi** [comment]
I just ended up adding a `Thread.sleep` before capturing the screenshots as a quick and dirty workaround. I know that this kinda defeats one of the purposes of this library, but it got the job done for the time being.

**Comment by giljulio** [comment]
Disabling animation of the TextInputLayout does the trick `layout.setHintAnimationEnabled(false);`
