### ISSUE TITLE
Provide information about failed tests

### ISSUE THREAD

**Issue by chriswiesner** [facebook/screenshot-tests-for-android#66]
Hi,

as far as i've seen if you run the verify command on CI and there is a regression in one test, the whole build just fails and you don't have information where the regression actually happened.
how are we supposed to know then in which test the regression happened?

**Comment by tdrhq** [comment]
An you show me what the output looks like and what you would've expected?

On May 4, 2017 3:14 AM, "Christoph Wiesner" <notifications@github.com>
wrote:

Hi,

as far as i've seen if you run the verify command on CI and there is a
regression in one test, the whole build just fails and you don't have
information where the regression actually happened.
how are we supposed to know then in which test the regression happened?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/screenshot-tests-for-android/issues/66>, or mute
the thread

**Comment by chriswiesner** [comment]
Sorry I got something wrong. Build output states of course which images where not identical.

Still one thing:
if you have 2 tests failing only the first regression is logged bc. you immediately fail the build.

Additionally it would be nice to have a html summary which shows the to images side-by-side.

**Comment by xiphirx** [comment]
Merging into #125
