### ISSUE TITLE
Can't take screenshot of activity with alert dialog

### ISSUE THREAD

**Issue by just-kip** [facebook/screenshot-tests-for-android#70]
```
class MainActivity: Activity() {
    ...
    fun showDialog() {
        alert(message = "helll") {
            positiveButton(android.R.string.ok)
        }.show()
    }
    ...
}
```

in espresso test 

```
@Test
fun test_alert_dialog() {
    val activity = activityRule.activity
    activity.runOnUiThread {
        activity.showDialog()
    }
    SystemClock.sleep(5000) //tried without it, result is same
    Screenshot.snapActivity(activity).record()
}
```
In emulator dialog appears, but screenshot record only activity, without dialog

**Comment by xiphirx** [comment]
This is because a `Dialog` is in a completely separate `Window` than your `Activity`. If you wish to capture your `Dialog` then do `Screenshot.snap(dialog.getWindow().getDecorView()).record()`

**Comment by japplin** [comment]
Is there a way I can get access to the dialog from the activity? Without adding some methods for testing typically an activity doesn't expose the dialog it's showing.

**Comment by xiphirx** [comment]
There are reflection hacks you can do to iterate over the active windows from the window manager, otherwise no.

In general, you shouldn't be testing that the activity is showing a dialog through a screenshot test, that is more of an instrumentation test. You would just create the dialog directly for the screenshot test to ensure that it looks correct.

**Comment by yasitha999** [comment]
I tried what @xiphirx suggested, `Screenshot.snap(dialog.getWindow().getDecorView()).record()`

It throws a NPE, has anyone had any success with capturing screenshots on dialogs?

`11:56:51 V/InstrumentationResultParser: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewRootImpl.addWindowCallbacks(android.view.WindowCallbacks)' on a null object reference`

**Comment by ApoloRossi** [comment]
I'm facing the exactly the same problem that leads to that unsolved issue:

https://github.com/facebook/screenshot-tests-for-android/issues/242

**Comment by ApoloRossi** [comment]
I could do the test in two different ways:

1. The first one is like @japplin said but it's not the suitable way. In the activity I had to store the dialog in a variable and expose this variable in a way that on the screenshot test I could access this dialog and snap it.

`Screenshot.snap(dialog.dialog?.window?.decorView).record()`

2. The second way I created a specific test for the dialog as @xiphirx said. Instead of has the same test for activity and dialog ( that should be an instrumented test ) I created specific test for each screens. Then I created a generic activity that calls the dialog only:
```
activityRule.activity.addDialogFragment(dialog)
InstrumentationRegistry.getInstrumentation().waitForIdleSync()
Screenshot.snap(dialog.dialog?.window?.decorView).record()
```
To avoid the `java.lang.NullPointerException` I used the `waitForIdleSync()` as it's told on the issue https://github.com/facebook/screenshot-tests-for-android/issues/242 and everything worked fine! 

In a certain way the first option looks a good way to keep focused tests for all elements on the screen because if you have a lot of behaviors inside the same screen looks ok do not implement using instrumentation tests but expose and store the dialog it's somethings that bothers me.

Well, I hope it helps someone!
